security:
    access_decision_manager:
        strategy: unanimous

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        database_users:
            entity: { class: AppBundle:User }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: true

            # Let user to login by username and pass
            form_login:
                check_path: security_login_check
                login_path: security_login_form
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret'
                lifetime: 86400 # 1 день
                path: /
            logout:
                path: security_logout
                target: home # переадресация на этот route name после logout

    access_control:
        - { path: ^/(%app_locales%)/admin, roles: ROLE_ADMIN }
