<?php

namespace AppBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use AppBundle\Entity\User;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadAppBundleEntityUser extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetadata(User::class)->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);
    
        $item1 = new User();
        $this->addReference('_reference_AppBundleEntityUser1', $item1);
        $item1->setName("Alex");
        $item1->setSurname("Lat");
        $item1->setUsername("alex");
        $item1->setEmail("latunov@ok.de");
        $item1->setPassword("\$2y\$13\$VH39pG96J5eJHYfgU5RyLeLHRaGysXMj2Nj/xIT1T0my4eJdaHwhK");
        $item1->setIsActive(true);
        $item1->setToken("VYq2eg4RYmwHddS2Awj-SXU2i4OPMe8MglWZFTEt3to");
        $item1->setRoles(unserialize('a:1:{i:0;s:10:"ROLE_ADMIN";}'));

        $manager->persist($item1);

        $item2 = new User();
        $this->addReference('_reference_AppBundleEntityUser2', $item2);
        $item2->setName("Mad");
        $item2->setSurname("Max");
        $item2->setUsername("max");
        $item2->setEmail("max@mail.com");
        $item2->setPassword("\$2y\$13\$F7t0DHPtS79Pckm7bj48j.hElODbyg0LJHh/edeftEyKGLQe4UQJi");
        $item2->setIsActive(true);
        $item2->setToken("Xi8vf7Ulxwa2b7DEfo5Q7Lb7mjDrzpv9j93rN9GCrmc");
        $item2->setRoles(unserialize('a:1:{i:0;s:9:"ROLE_USER";}'));

        $manager->persist($item2);

    
        $manager->flush();
    }

}
